<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class RealCardSeeder extends Seeder
{
    const CDN = 'https://cdn.piltoverarchive.com/cards/';

    public function run(): void
    {
        $c = Category::pluck('id', 'name');
        $nox = $c['Noxus'];      $ion = $c['Ionia'];       $plt = $c['Piltover'];
        $fre = $c['Freljord'];   $sha = $c['Shadow Isles']; $dem = $c['Demacia'];
        $zau = $c['Zaun'];       $bil = $c['Bilgewater'];   $ban = $c['Bandle City'];
        $voi = $c['Void'];       $tar = $c['Targon'];       $shu = $c['Shurima'];
        $ixt = $c['Ixtal'];      $neu = $c['Neutral'];

        // [ID, Name, Category, Rarity, Energy, Power, Might, Description, Price, Stock]
        $cards = [
            // ── ARCANE BOX SET (Verified via Screenshots) ─────────────────────
            ['ARC-001', 'Vi, Destructive', $plt, 'legendary', 2, 1, 3, "GANKING (I can move from battlefield to battlefield.)\nRecycle 1 from your trash: Give me +1 Might this turn.", 18.99, 22],
            ['ARC-002', 'Caitlyn, Patrolling', $plt, 'legendary', 3, 1, 3, "I must be assigned combat damage last.\n[TAP]: Deal damage equal to my Might to a unit at a battlefield. Use this ability only while I'm at a battlefield.", 21.99, 17],
            ['ARC-003', 'Heimerdinger, Inventor', $plt, 'legendary', 3, 1, 3, "[TAP]: Give me +1 Power this turn. When you play a spell, ready me.", 20.99, 18],
            ['ARC-004', 'Warwick, Hunter', $zau, 'legendary', 6, 2, 5, "When I'm at a battlefield, units at that battlefield have -1 Might.", 21.99, 17],
            ['ARC-005', 'Jinx, Rebel', $zau, 'legendary', 5, 2, 5, "When I'm at a battlefield, [TAP]: Deal 2 damage to all units at that battlefield.", 29.99, 12],
            ['ARC-006', 'Viktor, Leader', $zau, 'legendary', 4, 1, 4, "When I'm at a battlefield, you can play spells at that battlefield for 1 less Energy.", 25.99, 13],
            
            // ── ORIGINS SET (Verified via Screenshots) ────────────────────────
            ['OGN-001', 'Blazing Scorcher', $nox, 'common', 5, 0, 5, "ACCELERATE (You may pay 1 Energy as an additional cost to have me enter ready.)", 7.99, 40],
            ['OGN-002', 'Brazen Buccaneer', $bil, 'common', 6, 0, 5, "As you play me, you may discard a card as an additional cost. If you do, reduce my cost by 2.", 5.49, 55],
            ['OGN-003', 'Chemtech Enforcer', $nox, 'common', 4, 0, 5, "I have +1 Might for each of your other Chemtech units.", 2.99, 80],
            ['OGN-004', 'Cleave', $nox, 'common', 2, null, null, "Deal 1 damage to all units at a battlefield.", 1.99, 100],
            ['OGN-005', 'Disintegrate', $nox, 'rare', 2, null, null, "Pick a unit. The next time it takes damage this turn, destroy it.", 6.99, 45],
            ['OGN-006', 'Flame Chompers', $zau, 'common', 1, 0, 1, "When I'm discarded, play me for 0 Energy.", 2.49, 90],
            ['OGN-008', 'Get Excited!', $zau, 'rare', 3, null, null, "To play me, discard 1. Deal 3 damage to anything.", 8.99, 35],
            ['OGN-011', 'Magma Wurm', $fre, 'common', 8, 1, 8, "Other friendly units enter ready.", 9.99, 30],
            ['OGN-012', 'Noxus Hopeful', $nox, 'common', 4, 0, 4, "LEGION: I cost 2 less. (Get the effect if you've played another card this turn.)", 1.99, 100],
            ['OGN-013', 'Pouty Poro', $fre, 'common', 2, 0, 2, "DEFLECT: (Opponents must pay Energy to choose me with an ability or spell)", 2.49, 95],
            ['OGN-014', 'Sky Splitter', $fre, 'common', 8, 1, 0, "(Play on your turn or in showdowns.) This spell's Energy cost is reduced by the highest Might among units you control. Deal 5 to a unit at a battlefield.", 11.99, 25],
            ['OGN-015', 'Captain Farron', $nox, 'uncommon', 4, 1, 5, "Other friendly units here have ASSAULT (+1 Power while they're attackers.)", 7.49, 40],
            ['OGN-016', 'Dangerous Duo', $ban, 'uncommon', 3, 0, 3, "LEGION: When you play me, give a unit +2 Might this turn. (Get the effect if you've played another card this turn.)", 4.99, 60],
            ['OGN-017', 'Iron Ballista', $nox, 'uncommon', 3, 0, 0, "This enters exhausted. [Tap]: Deal 2 to a unit at a battlefield.", 2.99, 80],
            ['OGN-018', 'Noxus Saboteur', $nox, 'uncommon', 3, 0, 3, "Your opponents' HIDDEN cards can't be revealed here.", 4.49, 65],
            ['OGN-019', 'Raging Soul', $sha, 'uncommon', 4, 0, 4, "If you've discarded a card this turn, I have ASSAULT and GANKING. (+1 Power while I'm an attacker. I can move from battlefield to battlefield)", 5.99, 55],
            ['OGN-020', 'Scrapyard Champion', $ban, 'uncommon', 5, 1, 5, "LEGION: When you play me, discard 2, then draw 2. (Get the effect if you've played another card this turn.)", 7.99, 38],
            ['OGN-028', 'Draven, Showboat', $nox, 'rare', 5, 1, 3, "My might is increased by your points.", 6.99, 45],
            ['OGN-029', 'Falling Star', $tar, 'rare', 2, 2, 0, "Deal 3 to a unit. Deal 3 to a unit. (You can choose different units.)", 6.99, 42],
            ['OGN-030', 'Jinx, Demolitionist', $zau, 'rare', 3, 1, 4, "ACCELERATE (You may pay 1 energy as an additional cost to have me enter ready.) ASSAULT 2 (+2 power while I'm an attacker.) When you play me, discard 2.", 29.99, 12],
            ['OGN-030a', 'Jinx (Alt Art)', $zau, 'showcase', 3, 1, 4, "ACCELERATE (You may pay 1 energy as an additional cost to have me enter ready.) ASSAULT 2 (+2 power while I'm an attacker.) When you play me, discard 2.", 49.99, 5],
            ['OGN-031', 'Raging Firebrand', $tar, 'rare', 6, 1, 4, "When you play me, the next spell you play this turn costs 5 less.", 4.49, 65],
            ['OGN-032', 'Ravenborn Tome', $nox, 'rare', 3, 0, 0, "Errata: The next spell you play this turn deals 1 Bonus Damage. (Each instance of damage the spell deals is increased by 1.)", 3.99, 68],
            ['OGN-033', 'Shakedown', $nox, 'rare', 2, 1, 0, "REACTION: Choose an enemy unit. Deal 6 to it unless its controller has you draw 2.", 7.49, 38],
            ['OGN-034', 'Tryndamere, Barbarian', $fre, 'rare', 7, 2, 8, "When I conquer after an attack, if you assigned 5 or more excess damage to enemy units, you score 1 Point.", 14.99, 25],
            ['OGN-035', 'Vayne, Hunter', $dem, 'rare', 4, 1, 2, "ASSAULT 3 (+3 Might while I'm an attacker.) If an opponent controls a battlefield, I enter ready. When I conquer, you may pay 1 to return me to hand.", 15.99, 22],
            ['OGN-036', 'Vi, Destructive (Rare)', $plt, 'rare', 2, 1, 3, "GANKING (I can move from battlefield to battlefield.) Recycle 1 from your trash: Give me +1 Might this turn.", 12.99, 30],
            ['OGN-027', 'Darius', $nox, 'legendary', 6, 2, 6, "When I'm played, if the enemy Nexus has 10 or less health, I have +4 Might.", 24.99, 15],
            ['OGN-028', 'Draven', $nox, 'legendary', 3, 1, 3, "When I'm played or attack, create a Spinning Axe in hand.", 21.99, 18],
            ['OGN-034', 'Tryndamere', $fre, 'legendary', 8, 2, 7, "If I would die, I level up instead.", 19.99, 20],
            ['OGN-035', 'Vayne', $dem, 'legendary', 3, 1, 4, "When I'm played, create a Tumble in hand.", 22.99, 16],
            ['OGN-039', "Kai'Sa, Survivor", $voi, 'epic', 4, 0, 4, "ACCELERATE (You may pay 1 Energy as an additional cost to have me enter ready.) When I conquer, draw 1.", 26.99, 12],
            ['OGN-039a', "Kai'Sa, Survivor (Alt)", $voi, 'showcase', 4, 0, 4, "ACCELERATE (You may pay 1 Energy as an additional cost to have me enter ready.) When I conquer, draw 1.", 49.99, 5],
            ['OGN-040', 'Seal of Rage', $nox, 'rare', 0, null, null, "REACTIVE + ADD (Abilities that add resources can't be reacted to.)", 4.99, 60],
            ['OGN-041', 'Volibear', $fre, 'legendary', 10, 2, 9, "DEFLECT 2 (Opponents must pay 2 Energy to choose me with a spell or ability.) When I attack, deal 5 damage split among any number of enemy units here.", 23.99, 14],
            ['OGN-041a', 'Volibear, Furious (Alt)', $fre, 'showcase', 10, 2, 9, "DEFLECT 2 (Opponents must pay 2 Energy to choose me with a spell or ability.) When I attack, deal 5 damage split among any number of enemy units here.", 44.99, 5],
            ['OGN-042', 'Calm Rune', $ion, 'common', 0, null, null, "A common rune for the Ionia faction.", 3.49, 72],
            ['OGN-042a', 'Calm Rune (Alt)', $ion, 'showcase', 0, null, null, "A common rune for the Ionia faction.", 9.99, 10],
            ['OGN-042b', 'Calm Rune (Alt 2)', $ion, 'showcase', 0, null, null, "A common rune for the Ionia faction.", 9.99, 10],
            ['OGN-043', 'Charm', $ion, 'common', 1, null, null, "Move an enemy unit.", 1.99, 105],
            ['OGN-044', 'Clockwork Keeper', $shu, 'common', 2, 0, 2, "As you play me, you may pay 1 Energy as an additional cost. If you do, draw 1.", 4.49, 65],
            ['OGN-045', 'Defy', $ion, 'common', 1, null, null, "REACTIVE Counter a spell that costs no more than 4 Energy. (Spell shield logic.)", 7.99, 36],
            ['OGN-046', 'En Garde', $dem, 'common', 1, null, null, "REACTIVE Give a friendly unit +1 Might this turn, then an additional +1 Might this turn if it is the only unit you control here.", 2.49, 90],
            ['OGN-047', 'Find Your Center', $ion, 'common', 3, null, null, "ACTION If an opponent's score is within 3 points of the Victory Score, this costs 2 Energy less. Draw 1 and channel 1 rune exhausted.", 6.49, 45],
            ['OGN-048', 'Meditation', $ion, 'common', 2, null, null, "REACTIVE As an additional cost to play this, you may exhaust a friendly unit. If you do, draw 2. Otherwise, draw 1.", 3.99, 70],
            ['OGN-049', 'Playful Phantom', $sha, 'common', 5, 1, 5, "A spectral fighter from the Shadow Isles.", 5.49, 55],
            ['OGN-050', 'Rune Prison', $ion, 'common', 2, null, null, "ACTION Stun a unit.", 8.99, 33],
            ['OGN-051', 'Solari Shieldbearer', $tar, 'common', 3, 0, 2, "When you play me, stun a unit.", 2.99, 85],
            ['OGN-052', 'Stalwart Poro', $fre, 'common', 2, 0, 2, "SHIELD (+1 Might while I'm a defender.)", 1.99, 100],
            ['OGN-053', 'Stand United', $ion, 'common', 3, null, null, "HIDDEN (3) ACTION Buff a friendly unit. Buffs give an additional +1 Might to friendly units this turn.", 4.49, 62],
            ['OGN-054', 'Sunlit Guardian', $shu, 'common', 3, 0, 3, "SHIELD (+1 Might while I'm a defender.) TANK (I must be assigned combat damage first.)", 2.49, 88],
            ['OGN-055', 'Wielder of Water', $ion, 'common', 3, 0, 2, "While I'm attacking or defending alone, I have +2 Might.", 5.99, 52],
            ['OGN-056', 'Adaptatron', $plt, 'common', 4, 0, 3, "When I conquer, you may kill a gear. If you do, buff me.", 7.49, 40],
            ['OGN-057', 'Block', $ion, 'common', 2, null, null, "HIDDEN (1) ACTION Give a unit SHIELD 2 and TANK this turn.", 1.99, 110],
            ['OGN-058', 'Discipline', $ion, 'common', 2, null, null, "REACTIVE Give a unit +2 Might this turn. Draw 1.", 2.49, 95],
            ['OGN-059', 'Eclipse Herald', $tar, 'common', 7, 0, 7, "When you stun an enemy unit, ready me and give me +1 Power this turn.", 12.99, 22],
            ['OGN-060', 'Mask of Foresight', $ion, 'common', 2, null, null, "When a friendly unit attacks or defends alone, give it +1 Might this turn.", 5.99, 50],
            ['OGN-061', 'Poro Herder', $fre, 'uncommon', 3, 1, 3, "When you play me, if you control a Poro, buff me and draw 1. (If I don't have a buff, I get a +1 Might buff.)", 4.99, 58],
            ['OGN-062', 'Reinforce', $dem, 'uncommon', 5, null, null, "Look at the top 5 cards of your Main Deck. You may play a unit from among them. Its Energy cost is reduced by 3. Then recycle the remaining cards.", 6.49, 42],
            ['OGN-063', 'Spirit\'s Refuge', $ion, 'uncommon', 2, null, null, "When you play this, buff a friendly unit. (If it doesn't have a buff, it gets a +1 Might buff.) Friendly buffed units have REFLECT. (Opponents must pay 4 Energy to choose these units with a spell or ability.)", 3.99, 75],
            ['OGN-064', 'Wind Wall', $ion, 'uncommon', 3, null, null, "REACTION: Counter a spell.", 8.99, 32],
            ['OGN-065', 'Wizened Elder', $ion, 'uncommon', 4, 1, 4, "While I'm buffed, I have an additional +1 Might.", 2.99, 88],
            ['OGN-066', 'Ahri, Alluring', $ion, 'legendary', 5, 2, 4, "When I hold, you score 1 point. 'Remember this moment.'", 24.99, 12],
            ['OGN-066a', 'Ahri, Alluring (Showcase)', $ion, 'showcase', 5, 2, 4, "When I hold, you score 1 point. 'Remember this moment.'", 44.99, 5],
            ['OGN-067', 'Blitzcrank, Impassive', $zau, 'legendary', 5, 1, 5, "TANK (I must be assigned combat damage first.) When you play me to a battlefield, you may move an enemy unit to here. When I hold, return me to my owner's hand.", 22.99, 14],
            ['OGN-068', 'Caitlyn, Patrolling', $plt, 'legendary', 3, 1, 3, "I must be assigned combat damage last. Strike: Deal damage equal to my Might to a unit at a battlefield. Use this ability only while I'm at a battlefield.", 21.99, 16],
            ['OGN-069', 'Last Stand', $dem, 'rare', 3, null, null, "REACTION: Double a friendly unit's Might this turn. Give it TEMPORARY. (Kill it at the start of its controller's Beginning Phase, before scoring.)", 7.49, 35],
            ['OGN-070', 'Mageseeker Warden', $dem, 'rare', 6, 1, 5, "While I'm at a battlefield, opponents can only play units to their base. While I'm at a battlefield, spells and abilities can't ready enemy units and gear.", 5.99, 52],
            ['OGN-071', 'Party Favors', $ban, 'rare', 3, null, null, "Each other player chooses Cards or Runes. For each player that chooses Cards, you and that player each draw 1. For each player that chooses Runes, you and that player each channel 1 rune exhausted.", 4.49, 65],
            ['OGN-072', 'Solari Shrine', $tar, 'rare', 3, null, null, "When you kill a stunned enemy unit, you may exhaust this to draw 1.", 3.49, 70],
            ['OGN-073', 'Sona, Harmonious', $dem, 'legendary', 4, 1, 4, "While I'm at a battlefield, ready 4 friendly runes at the end of your turn.", 25.99, 11],
            ['OGN-074', 'Taric, Protector', $tar, 'legendary', 4, 1, 4, "SHIELD (+1 Might while I'm a defender.) TANK (I must be assigned combat damage first.) Other friendly units here have SHIELD.", 23.99, 13],
            ['OGN-075', 'Tasty Faefolk', $ion, 'rare', 7, 0, 6, "ACCELERATE (You may pay 1 Energy as an additional cost to have me enter ready.) DEATHKELL - Channel 2 runes exhausted and draw 1. (When I die, get the effect.)", 2.99, 80],
            ['OGN-076', 'Yasuo, Remorseful', $ion, 'legendary', 6, 1, 6, "When I attack, deal damage equal to my Might to an enemy unit here.", 24.99, 12],
            ['OGN-076a', 'Yasuo, Remorseful (Showcase)', $ion, 'showcase', 6, 1, 6, "When I attack, deal damage equal to my Might to an enemy unit here.", 44.99, 5],
            ['OGN-077', 'Zhonya\'s Hourglass', $ion, 'rare', 2, null, null, "HIDDEN (Hide now for 1 Energy to react with later for 1 Energy.) The next time a friendly unit would die, kill this instead. Recall that unit exhausted. (Send it to base. This isn't a move.)", 9.99, 28],
            ['OGN-078', 'Lee Sin, Ascetic', $ion, 'legendary', 5, 0, 5, "REACTION (Play any time, even before spells and abilities resolve.) Buff me. (If I don't have a buff, I get a +1 Might buff.) I can have any number of buffs.", 22.99, 15],
            ['OGN-078a', 'Lee Sin, Ascetic (Showcase)', $ion, 'showcase', 5, 0, 5, "REACTION (Play any time, even before spells and abilities resolve.) Buff me. (If I don't have a buff, I get a +1 Might buff.) I can have any number of buffs.", 42.99, 5],
            ['OGN-079', 'Leona, Zealot', $tar, 'legendary', 6, 1, 5, "When an opponent's score is within 3 points of the Victory Score, I enter ready. Stunned enemy units here have -3 Might, to a minimum of 1 Might.", 21.99, 17],
            ['OGN-080', 'Mystic Reversal', $ion, 'rare', 4, null, null, "REACTION: Gain control of a spell. You may make new choices for it.", 8.49, 32],
            ['OGN-081', 'Seal of Focus', $plt, 'rare', 0, null, null, "REACTION: (Abilities that add resources can't be reacted to.)", 3.49, 75],
            ['OGN-082', 'Whiteflame Protector', $tar, 'rare', 8, 1, 8, "When you play me, give a unit +8 Might this turn.", 6.99, 40],
            ['OGN-084', 'Consult the Past', $nox, 'rare', 4, null, null, "HIDDEN Draw 2.", 5.49, 55],
            ['OGN-085', 'Eager Apprentice', $plt, 'common', 3, 0, 3, "While I'm at a battlefield, the Energy costs for spells you play is reduced by 1, to a minimum of 1.", 1.49, 110],
            ['OGN-086', 'Falling Comet', $tar, 'common', 5, null, null, "ACTION: Deal 6 to a unit at a battlefield.", 2.49, 90],
            ['OGN-087', 'Jeweled Colossus', $tar, 'common', 5, 1, 5, "RESERVE SHIELD (+1 Might while I'm a defender.)", 4.49, 62],
            ['OGN-088', 'Lecturing Yordle', $ban, 'common', 3, 1, 2, "TANK (I must be assigned combat damage first.) When you play me, draw 1.", 2.99, 85],
            ['OGN-089', 'Mega-Mech', $ban, 'common', 7, 2, 8, "A colossal construct powered by Yordle ingenuity.", 8.99, 33],
            ['OGN-290', 'Mind Rune', $ion, 'common', 0, null, null, "A core resource used for Ionian techniques.", 0.99, 500],
            ['OGN-090', 'Orb of Regret', $sha, 'common', 1, null, null, "ACTION: Give a unit -1 Might this turn, to a minimum of 1 Might.", 1.99, 120],
            ['OGN-091', 'Pit Crew', $ban, 'common', 3, 1, 3, "When you play a gear, ready me.", 2.49, 95],
            ['OGN-092', 'Riptide Rex', $bil, 'common', 6, 2, 6, "When you play me, deal 6 to an enemy unit at a battlefield.", 7.49, 38],
            ['OGN-093', 'Smoke Screen', $zau, 'common', 2, null, null, "REACTION: Give a unit -1 Might this turn, to a minimum of 1 Might.", 1.49, 150],
            ['OGN-094', 'Sprite Call', $ion, 'common', 3, null, null, "HIDDEN Play a ready 3/3 Sprite unit token with TEMPORARY.", 3.49, 72],
            ['OGN-095', 'Stupefy', $ban, 'common', 1, null, null, "REACTION: Give a unit -1 Might this turn, to a minimum of 1 Might. Draw 1.", 2.49, 92],
            ['OGN-096', 'Watchful Sentry', $fre, 'common', 2, 1, 1, "DEATHKELL - Draw 1.", 1.29, 180],
            ['OGN-097', 'Blastcone Fae', $ban, 'common', 2, 1, 2, "HIDDEN When you play me, give a unit -2 Might this turn, to a minimum of 1 Might.", 2.49, 98],
            ['OGN-098', 'Energy Conduit', $plt, 'common', 3, null, null, "REACTION: (Abilities that add resources can't be reacted to.)", 3.99, 65],
            ['OGN-099', 'Garbage Grabber', $plt, 'common', 2, null, null, "Recycle 3 from your trash. ACTION: Draw 1.", 1.99, 115],
            ['OGN-100', 'Gemcraft Seer', $tar, 'common', 3, 1, 3, "RESERVE Other friendly units have REFLECT.", 4.49, 60],
            ['OGN-101', 'Mushroom Pouch', $ban, 'common', 2, null, null, "At the start of your Beginning Phase, if you control a facedown card at a battlefield, draw 1.", 2.99, 85],
            ['OGN-102', 'Portal Rescue', $ban, 'common', 3, null, null, "ACTION: Banish a friendly unit, then play it to base, ignoring its cost.", 4.99, 52],
            ['OGN-103', 'Ravenbloom Student', $nox, 'common', 2, 1, 2, "When you play a spell, give me +1 Might this turn.", 1.49, 140],
            ['OGN-104', 'Retreat', $ion, 'common', 1, null, null, "REACTION: Return a friendly unit to its owner's hand. Its owner channels 1 rune exhausted.", 2.49, 90],
            ['OGN-105', 'Singularity', $ion, 'common', 6, null, null, "Deal 6 to each of up to two units.", 7.99, 36],
            ['OGN-106', 'Sprite Mother', $ion, 'common', 4, 1, 3, "When you play me, play a ready 3/3 Sprite unit token with TEMPORARY.", 3.49, 78],
            ['OGN-107', 'Ava Achiever', $ban, 'legendary', 5, 2, 4, "When I attack, you may pay 2 Energy to play a card with HIDDEN from your hand here, ignoring its cost.", 23.99, 12],
            ['OGN-108', 'Convergent Mutation', $ion, 'common', 2, null, null, "REACTION: Choose a friendly unit. Increase its Might until it equals the Might of another friendly unit.", 2.49, 110],
            ['OGN-110', 'Stun Shield', $tar, 'common', 2, null, null, "REACTION: Give a unit SHIELD 3 this turn. If it is stunned, draw 1.", 2.49, 90],
            ['OGN-111', 'Towering Stone', $tar, 'common', 5, 1, 6, "SHIELD (+1 Might while I'm a defender.)", 3.99, 65],
            ['OGN-112', 'Yordle Squire', $ban, 'common', 1, 0, 1, "When you play me, create a Tiny Spear in hand.", 1.49, 150],
            ['OGN-113', 'Zoe, Sparkle', $tar, 'legendary', 2, 1, 2, "When you play a spell, create a Supercool Starchart in hand.", 22.99, 14],
            ['OGN-114', 'Teemo, Scout', $ban, 'legendary', 1, 1, 1, "Strike: Plant 5 Poison Mushrooms in the enemy's deck.", 25.99, 12],
            ['OGN-114a', 'Teemo, Scout (Showcase)', $ban, 'showcase', 1, 1, 1, "Strike: Plant 5 Poison Mushrooms in the enemy's deck.", 49.99, 5],
            ['OGN-115', 'Viktor, Leader', $zau, 'legendary', 4, 1, 4, "When I'm at a battlefield, you can play spells at that battlefield for 1 less Energy.", 21.99, 16],
            ['OGN-116', 'Braum, Shield', $fre, 'legendary', 4, 0, 5, "TANK (I must be assigned combat damage first.) REGENERATION (Ready me at the start of each Beginning Phase.)", 22.99, 15],
            ['OGN-117', 'Garen, Knight', $dem, 'legendary', 5, 1, 5, "REGENERATION (Ready me at the start of each Beginning Phase.)", 19.99, 20],
            ['OGN-118', 'Lee Sin, Monk', $ion, 'legendary', 5, 0, 5, "REACTION Buff me. (If I don't have a buff, I get a +1 Might buff.) I can have any number of buffs.", 22.99, 14],
            ['OGN-119', 'Lucian, Hunter', $dem, 'legendary', 2, 1, 2, "QUICK ATTACK (I strike before my blocker.)", 21.99, 16],
            ['OGN-120', 'Miss Fortune', $bil, 'legendary', 3, 1, 3, "When I'm at a battlefield, deal 1 to all enemy units here at the start of combat.", 24.99, 12],
            ['OGN-121', 'Sett, Boss', $ion, 'legendary', 5, 2, 5, "CHALLENGER (I can choose which unit blocks me.)", 23.99, 15],
            ['OGN-122', 'Swain, General', $nox, 'legendary', 5, 1, 4, "Fearsome: Only units with 3 or more Might can block me.", 21.99, 16],
            ['OGN-123', 'Thresh, Jailer', $sha, 'legendary', 5, 1, 6, "CHALLENGER (I can choose which unit blocks me.)", 22.99, 14],
            ['OGN-124', 'Aurelion Sol', $tar, 'legendary', 10, 3, 10, "FURY: When I kill a unit, I gain +1/+1. SPELLSHIELD.", 29.99, 10],
            ['OGN-125', 'Nautilus', $bil, 'legendary', 7, 0, 12, "TOUGH: I take 1 less damage from all sources.", 19.99, 18],
            ['OGN-126', 'Soraka', $tar, 'legendary', 3, 1, 6, "When I attack, heal my blocker 4. If I do, score 1 point.", 21.99, 16],
            ['OGN-127', 'Zoe, Messenger', $tar, 'legendary', 2, 1, 2, "When you play a spell, create a Supercool Starchart in hand.", 22.99, 14],
            ['OGN-128', 'Apprehend', $nox, 'uncommon', 2, null, null, "ACTION: Stun a unit. If you control Darius, ready him.", 3.49, 75],
            ['OGN-129', 'Blinding Assault', $dem, 'uncommon', 2, null, null, "ACTION: Play a 2/1 Valor with CHALLENGER.", 2.99, 85],
            ['OGN-130', 'Death Ray', $zau, 'uncommon', 1, null, null, "ACTION: Deal 1 to a unit. Create a Death Ray Mk 2 in your deck.", 1.99, 120],
            ['OGN-131', 'Eye of the Dragon', $ion, 'uncommon', 2, 0, 2, "If you've played 2+ spells this turn, play a Dragonling.", 4.49, 65],
            ['OGN-132', 'Gifts From Beyond', $tar, 'uncommon', 1, null, null, "ACTION: Choose a Moon Weapon to create in hand.", 2.49, 90],
            ['OGN-133', 'Guiding Touch', $tar, 'uncommon', 2, null, null, "ACTION: Heal 2. Draw 1.", 1.49, 140],
            ['OGN-134', 'Hush', $tar, 'uncommon', 3, null, null, "REACTION: Silence a unit this turn.", 8.99, 32],
            ['OGN-135', 'Pakaa Cub', $ixt, 'uncommon', 2, 1, 2, "When you play another Ixtal unit, give me +1/+0.", 1.99, 110],
            ['OGN-136', 'Pale Cascade', $tar, 'uncommon', 2, null, null, "REACTION: Give a unit +1/+1 this turn. Draw 1.", 2.49, 95],
            ['OGN-137', 'Star Shaping', $tar, 'uncommon', 5, null, null, "ACTION: Heal 5. Create a Celestial card in hand.", 3.49, 78],
            ['OGN-138', 'Catalyst of Aeons', $neu, 'uncommon', 5, null, null, "ACTION: Heal 3. Gain an extra Energy slot.", 6.49, 45],
            ['OGN-139', 'Deny', $ion, 'uncommon', 4, null, null, "REACTION: Counter a spell.", 9.99, 25],
            ['OGN-140', 'Single Combat', $dem, 'uncommon', 2, null, null, "REACTION: Two units strike each other.", 1.99, 150],
            ['OGN-141', 'Sunburst', $tar, 'uncommon', 6, null, null, "ACTION: Deal 6 to a unit. Silence it if it's Daybreak.", 7.49, 38],
            ['OGN-142', 'Vengeance', $sha, 'uncommon', 6, null, null, "ACTION: Destroy a unit.", 9.49, 30],
            ['OGN-143', 'Zenith Blade', $tar, 'uncommon', 3, null, null, "ACTION: Give a unit +1/+2 and OVERWHELM.", 2.99, 85],
            ['OGN-144', 'Aggressive Strategy', $nox, 'common', 1, null, null, "Give an ally +1 Power this turn.", 0.99, 200],
            ['OGN-145', 'Barkbeast', $sha, 'common', 1, 1, 1, "When an ally dies, I gain +1/+1.", 1.29, 180],
            ['OGN-146', 'Culling Strike', $nox, 'common', 3, null, null, "Destroy a unit with 3 or less Might.", 4.49, 62],
            ['OGN-147', 'Death Mark', $sha, 'common', 3, null, null, "Transfer Ephemeral from an ally to an enemy.", 3.99, 68],
            ['OGN-148', 'Elixir of Iron', $fre, 'common', 1, null, null, "Give an ally +0/+2 this turn.", 0.99, 250],
            ['OGN-149', 'Fleetfeather Tracker', $dem, 'common', 1, 2, 1, "CHALLENGER.", 1.49, 160],
            ['OGN-150', 'Glimpse Beyond', $sha, 'common', 2, null, null, "Kill an ally to draw 2.", 2.49, 100],
            ['OGN-151', 'Make it Rain', $bil, 'common', 2, null, null, "Deal 1 to three random enemies.", 1.99, 140],
            ['OGN-152', 'Mystic Shot', $plt, 'common', 2, null, null, "Deal 2 to anything.", 1.49, 200],
            ['OGN-153', 'Noxian Fervor', $nox, 'common', 3, null, null, "Deal 3 to an ally to deal 3 to anything.", 2.49, 95],
            ['OGN-154', 'Primal Strength', $ixt, 'common', 2, null, null, "Give an ally +2/+2 this turn.", 1.29, 180],
            ['OGN-155', 'Qiyana', $ixt, 'legendary', 5, 2, 5, "When I'm played, choose an element. I gain a bonus based on it.", 24.99, 12],
            ['OGN-156', 'Relentless Pursuit', $dem, 'common', 3, null, null, "Ready your units.", 5.99, 50],
            ['OGN-157', 'Sharpsight', $dem, 'common', 2, null, null, "Give an ally +2/+2 and I can block Elusives.", 1.99, 130],
            ['OGN-158', 'Troll Chant', $fre, 'common', 2, null, null, "Give an ally +0/+2 and an enemy -2/-0 this turn.", 1.49, 160],
            ['OGN-159', 'Warwick', $zau, 'legendary', 6, 1, 5, "CHALLENGER. When I kill a unit, heal me 3.", 22.99, 14],
            ['OGN-160', 'Dazzling Aurora', $tar, 'rare', 9, 0, 0, "ACTION: Stun all enemy units. They can't be readied this turn.", 11.99, 15],
            ['OGN-161', 'Deadbloom Predator', $sha, 'rare', 8, 1, 8, "LIFESTEAL. When I'm played, toss 3.", 5.99, 42],
            ['OGN-162', 'Miss Fortune', $bil, 'legendary', 5, 1, 5, "When allies attack, deal 1 to all enemies and the enemy Nexus.", 24.99, 12],
            ['OGN-162a', 'Miss Fortune (Alt Art)', $bil, 'showcase', 5, 1, 5, "When allies attack, deal 1 to all enemies and the enemy Nexus.", 44.99, 5],
            ['OGN-163', 'Seal of Strength', $tar, 'rare', 0, 0, 0, "REACTION: Give a unit +2/+2 this turn.", 3.49, 80],
            ['OGN-164', 'Sett, Brawler', $ion, 'legendary', 4, 1, 4, "CHALLENGER. When I strike, I can't take damage or die this turn.", 23.99, 14],
            ['OGN-164a', 'Sett (Alt Art)', $ion, 'showcase', 4, 1, 4, "CHALLENGER. When I strike, I can't take damage or die this turn.", 43.99, 5],
            ['OGN-165', 'Cemetery Attendant', $sha, 'rare', 1, 0, 1, "When an ally dies, grant me +1/+1.", 1.99, 110],
            ['OGN-166', 'Chaos Rune', $neu, 'common', 0, 0, 0, "A chaotic element used in unpredictable magic.", 0.99, 500],
            ['OGN-166a', 'Chaos Rune (Alt A)', $neu, 'showcase', 0, 0, 0, "A chaotic element used in unpredictable magic.", 4.99, 50],
            ['OGN-166b', 'Chaos Rune (Alt B)', $neu, 'showcase', 0, 0, 0, "A chaotic element used in unpredictable magic.", 4.99, 50],
            ['OGN-167', 'Ember Monk', $ban, 'rare', 3, 0, 3, "While I'm at a battlefield, friendly spells deal 1 more.", 4.49, 65],
            ['OGN-168', 'Fight or Flight', $neu, 'rare', 1, 0, 0, "ACTION: Choose to draw 1 or grant a unit +2/+0.", 2.99, 85],
            ['OGN-169', 'Gust', $ion, 'common', 1, 0, 0, "REACTION: Recall an ally or stun an enemy unit.", 1.49, 160],
            ['OGN-170', 'Morbid Return', $sha, 'common', 2, 0, 0, "ACTION: Revive the last ally that died this turn.", 2.49, 95],
            ['OGN-171', 'Mystic Poro', $fre, 'common', 2, 0, 2, "ELUSIVE.", 1.99, 120],
            ['OGN-172', 'Rebuke', $dem, 'common', 2, 0, 0, "ACTION: Deal 3 to a unit that struck this turn.", 1.49, 150],
            ['OGN-173', 'Ride the Wind', $ion, 'common', 2, 0, 0, "Give an ally ELUSIVE and +1/+0 this turn.", 1.99, 130],
            ['OGN-174', 'Sai Scout', $shu, 'common', 6, 0, 5, "When I'm played, if you have a landmark, grant me ELUSIVE.", 4.49, 62],
            ['OGN-175', 'Shipyard Skulker', $bil, 'common', 3, 0, 3, "ELUSIVE. When I conquer, draw 1.", 2.49, 92],
            ['OGN-176', 'Sneaky Deckhand', $bil, 'common', 3, 0, 2, "When I'm played, create a Powder Keg.", 1.49, 180],
            ['OGN-177', 'Stealthy Pursuer', $shu, 'common', 4, 0, 4, "ELUSIVE. When I strike the Nexus, create a Poison Puffcap.", 3.49, 72],
            ['OGN-178', 'Undercover Agent', $nox, 'common', 5, 0, 5, "ELUSIVE. When I conquer, the enemy loses 1 point.", 5.99, 48],
            ['OGN-179', 'Acceptable Losses', $nox, 'common', 1, 0, 0, "Kill an ally to deal 4 to a unit.", 0.99, 200],
            ['OGN-180', 'Fading Memories', $sha, 'common', 4, 0, 0, "Create an Ephemeral copy of a unit in hand.", 4.49, 65],
            ['OGN-181', 'Pack of Wonders', $ban, 'common', 2, 0, 0, "ACTION: Create a random 1-cost unit in hand. It costs 0.", 2.99, 88],
            ['OGN-182', 'Scrapheap', $plt, 'common', 2, 0, 0, "ACTION: Create a random gear in hand.", 1.99, 115],
            ['OGN-183', 'Stacked Deck', $bil, 'common', 1, 0, 0, "ACTION: Look at the top 3 cards of your deck. Put them back in any order.", 0.99, 250],
            ['OGN-216', 'Soaring Scout', $fre, 'common', 2, 0, 1, "ELUSIVE. When you play a spell, grant me +1/+1.", 1.49, 110],
            ['OGN-217', 'Trifarian Gloryseeker', $nox, 'common', 2, 2, 0, "CHALLENGER. I can't block.", 2.49, 95],
            ['OGN-218', 'Vanguard Captain', $dem, 'common', 3, 3, 0, "When I'm played, grant all allies in the deck +1/+1.", 4.49, 62],
            ['OGN-219', 'Vanguard Sergeant', $dem, 'common', 4, 4, 0, "When I'm played, create a For Demacia! in hand.", 5.99, 50],
            ['OGN-220', 'Facebreaker', $nox, 'rare', 2, 0, 0, "ACTION: Stun a unit. If it has 3 or less Might, deal 2 to it.", 3.49, 75],
            ['OGN-221', 'Imperial Decree', $nox, 'rare', 5, 0, 0, "ACTION: Deal 4 to the enemy Nexus. Draw 1.", 6.99, 42],
            ['OGN-222', 'Noxian Drummer', $nox, 'common', 3, 3, 0, "CHALLENGER. When I'm played, grant an ally +1/+0.", 1.99, 130],
            ['OGN-223', 'Peak Guardian', $tar, 'common', 6, 5, 0, "SHIELD. When I'm played, stun a unit.", 4.49, 68],
            ['OGN-224', 'Salvage', $bil, 'common', 2, 0, 0, "ACTION: Draw 2. Toss 2.", 2.49, 92],
            ['OGN-225', 'Solari Chief', $tar, 'common', 5, 4, 0, "SHIELD. Other allies have +1/+1.", 3.99, 70],
            ['OGN-226', 'Spectral Matron', $sha, 'rare', 8, 4, 0, "When I'm played, play an exact copy of a unit from hand.", 9.99, 25],
            ['OGN-227', 'Symbol of the Solari', $tar, 'common', 1, 0, 0, "Grant a unit SHIELD.", 0.99, 200],
            ['OGN-228', 'Vanguard Helm', $dem, 'common', 2, 0, 0, "Grant an ally +1/+3.", 1.99, 120],
            ['OGN-229', 'Vengeance', $sha, 'rare', 4, 0, 0, "ACTION: Destroy a unit.", 8.99, 32],
            ['OGN-230', 'Albus Ferros', $plt, 'rare', 4, 3, 0, "When I'm played, create a Jayce in hand.", 6.49, 45],
            ['OGN-231', 'Commander Ledros', $sha, 'rare', 6, 8, 0, "When I'm played, deal damage to the enemy Nexus equal to half its health.", 12.99, 15],
            ['OGN-232', 'Fiora, Victorious', $dem, 'legendary', 4, 0, 4, "CHALLENGER. When I've killed 4 units and survived, you win the game.", 24.99, 12],
            ['OGN-233', 'Grand Strategem', $nox, 'rare', 6, 0, 0, "ACTION: Ready all allies. Grant them +1/+1.", 9.49, 30],
            ['OGN-234', 'Harnessed Dragon', $dem, 'common', 8, 6, 0, "FURY. CHALLENGER.", 5.99, 48],
            ['OGN-235', 'Karma, Channeler', $ion, 'legendary', 6, 6, 0, "When I'm enlightened, I double every spell you play.", 22.99, 14],
            ['OGN-236', 'Karthus, Eternal', $sha, 'legendary', 4, 3, 0, "When I die, deal 1 to all enemies.", 21.99, 16],
            ['OGN-237', 'King\'s Edict', $dem, 'rare', 6, 0, 0, "ACTION: Capture a unit.", 7.49, 38],
            ['OGN-238', 'Leona, Determined', $tar, 'legendary', 4, 0, 4, "When you trigger a Daybreak, stun an enemy.", 21.99, 15],
            ['OGN-239', 'Machine Evangel', $zau, 'rare', 5, 4, 0, "When I'm played, create a 0-cost spell in hand.", 5.99, 36],
            ['OGN-240', 'Sett, Kingpin', $ion, 'legendary', 4, 5, 0, "CHALLENGER. When I strike, I can't take damage or die.", 23.99, 14],
            ['OGN-241', 'Shen, Kinniku', $ion, 'legendary', 3, 3, 0, "When an ally is supported, grant it BARRIER.", 19.99, 20],
            ['OGN-242', 'Baited Hook', $bil, 'rare', 3, 0, 0, "ACTION: Choose a unit. An ally and that unit strike each other.", 3.49, 78],
            ['OGN-243', 'Darius, Executioner', $nox, 'legendary', 6, 6, 0, "OVERWHELM. When I'm played, if the enemy Nexus has 10 or less health, grant me +4/+0.", 24.99, 12],
            ['OGN-244', 'Divine Judgment', $tar, 'rare', 8, 0, 0, "REACTION: An ally can't take damage or die this turn.", 11.99, 18],
            ['OGN-245', 'Seal of Unity', $neu, 'rare', 0, 1, 0, "REACTION: (Abilities that add resources can't be reacted to.)", 3.49, 80],
            ['OGN-246', 'Viktor, Leader', $zau, 'legendary', 4, 0, 4, "When I'm played, create a Hex Core Upgrade in hand.", 21.99, 16],
            ['OGN-247', 'Kai\'Sa, Daughter of the Void', $voi, 'legendary', 3, 3, 0, "QUICK ATTACK. When I've seen you play 2+ cards with keywords, I evolve.", 23.99, 14],
            ['OGN-248', 'Icathian Rain', $voi, 'rare', 7, 0, 0, "ACTION: Deal 1 to all enemies for each keyword on allies.", 8.99, 32],
            ['OGN-249', 'Volibear, Relentless Storm', $fre, 'legendary', 10, 2, 9, "OVERWHELM. When I attack, deal 4 to three random enemies.", 29.99, 10],
            ['OGN-250', 'Stormbringer', $fre, 'rare', 6, 0, 0, "ACTION: Deal 4 to three random enemies.", 7.49, 38],
            ['OGN-251', 'Jinx, Loose Cannon', $zau, 'legendary', 4, 4, 0, "When your hand is empty, I level up.", 25.99, 12],
            ['OGN-252', 'Super Mega Death Rocket!', $zau, 'rare', 4, 0, 0, "ACTION: Deal 4 to the enemy Nexus and 1 to all enemies.", 9.99, 25],
            ['OGN-253', 'Hand of Noxus', $nox, 'common', 2, 0, 0, "ACTION: Give an ally +3/+0 this turn.", 1.49, 150],
            ['OGN-254', 'Noxian Guillotine', $nox, 'rare', 4, 0, 0, "ACTION: Destroy a damaged unit. You can cast this again.", 6.99, 40],
            ['OGN-255', 'Nine-Tailed Fox', $ion, 'common', 2, 0, 0, "When I'm played, create a Fox-Fire in hand.", 1.99, 120],
            ['OGN-256', 'Fox-Fire', $ion, 'common', 3, 0, 0, "ACTION: Deal 2 to a unit. It can't block this turn.", 2.49, 95],
            ['OGN-257', 'Blind Monk', $ion, 'common', 2, 0, 0, "When I'm played, create a Dragon's Rage in hand.", 1.49, 160],
            ['OGN-258', 'Dragon\'s Rage', $ion, 'rare', 4, 0, 0, "ACTION: An ally and an enemy unit strike each other.", 4.49, 65],
            ['OGN-259', 'Unforgiven', $ion, 'common', 3, 0, 0, "ACTION: Give an ally +2/+0 and QUICK ATTACK this turn.", 1.99, 130],
            ['OGN-260', 'Last Breath', $ion, 'rare', 3, 0, 0, "ACTION: When a unit dies this turn, create a copy of it in hand.", 5.99, 45],
            ['OGN-261', 'Radiant Dawn', $tar, 'rare', 6, 0, 0, "ACTION: Grant all allies +1/+1. Stun an enemy.", 7.49, 35],
            ['OGN-262', 'Zenith Blade', $tar, 'common', 3, 0, 0, "ACTION: Grant an ally +1/+2 and OVERWHELM.", 2.99, 85],
            ['OGN-263', 'Swift Scout', $ban, 'common', 1, 0, 0, "ELUSIVE. When I strike, create a Poison Puffcap.", 1.29, 180],
            ['OGN-265', 'Guerilla Warfare', $ban, 'common', 2, 0, 0, "ACTION: Give an ally +1/+1 and ELUSIVE this turn.", 1.99, 140],
            ['OGN-266', 'Siphon Power', $zau, 'rare', 2, null, null, "Sig. Spell: +1/-1 Might buff/debuff.", 3.49, 75],
            ['OGN-267', 'Bounty Hunter', $bil, 'rare', 2, null, null, "Sig. Spell: Give [BANKING].", 2.99, 85],
            ['OGN-268', 'Make it Rain', $bil, 'common', 1, null, null, "Sig. Spell: Deal 1 to three units.", 1.49, 200],
            ['OGN-269', 'The Boss', $ion, 'rare', 1, null, null, "Sig. Spell: Ready friendly unit.", 4.49, 62],
            ['OGN-270', 'Facebreaker', $ion, 'rare', 3, null, null, "Sig. Spell: Move and stun enemy unit.", 3.99, 68],
            ['OGN-271', 'Recruit', $neu, 'common', 1, 1, 1, "To strike against any of us is to strike against all of us!", 0.49, 1000],
            ['OGN-272', 'Recruit (Noxus)', $neu, 'common', 1, 1, 1, "Few earn the right to call themselves Trifarian.", 0.49, 1000],
            ['OGN-273', 'Recruit (Zaun)', $neu, 'common', 1, 1, 1, "We are the future.", 0.49, 1000],
            ['OGN-274', 'Sprite', $neu, 'common', 1, 1, 1, "Dreams rarely linger, but the dreamer is still changed.", 0.49, 1000],
            ['OGN-275', 'Altar to Unity', $neu, 'rare', 0, 0, 0, "BATTLEFIELD: When you hold here, play a Recruit unit token in your base.", 9.99, 20],
            ['OGN-276', 'Aspirant\'s Climb', $neu, 'rare', 0, 0, 0, "BATTLEFIELD: Increase the points needed to win the game by 1.", 14.99, 15],
            ['OGN-277', 'Back-Alley Bar', $zau, 'rare', 0, 0, 0, "BATTLEFIELD: When a unit moves from here, give it +1 Might this turn.", 12.99, 18],
            ['OGN-278', 'Bandle Tree', $ban, 'rare', 0, 0, 0, "BATTLEFIELD: You may hide an additional card here.", 15.99, 12],
            ['OGN-279', 'Fortified Position', $dem, 'rare', 0, 0, 0, "BATTLEFIELD: When you defend here, choose a unit. It gains [Shield] 2.", 11.99, 22],
            ['OGN-280', 'Grove of the God-Willow', $ion, 'rare', 0, 0, 0, "BATTLEFIELD: When you hold here, draw 1.", 13.99, 20],
            ['OGN-281', 'Hallowed Tomb', $sha, 'rare', 0, 0, 0, "BATTLEFIELD: When you hold here, return your Champion from trash to Zone.", 16.99, 10],
            ['OGN-282', 'Monastery of Hirana', $ion, 'rare', 0, 0, 0, "BATTLEFIELD: When you conquer, spend 1 Energy to buff [Shield] 1 and draw 1.", 12.49, 25],
            ['OGN-283', 'Navori Fighting Pit', $ion, 'rare', 0, 0, 0, "BATTLEFIELD: When you hold here, buff a unit here (+1 Might).", 10.99, 30],
            ['OGN-284', 'Obelisk of Power', $shu, 'rare', 0, 0, 0, "BATTLEFIELD: At start of phase, player channels 1 rune. (Note: Competitive Banned)", 19.99, 5],
            ['OGN-285', 'Reaver\'s Row', $bil, 'rare', 0, 0, 0, "BATTLEFIELD: When you defend here, move a friendly unit to base. (Note: Competitive Banned)", 14.99, 8],
            ['OGN-286', 'Reckoner\'s Arena', $nox, 'rare', 0, 0, 0, "BATTLEFIELD: When you hold here, activate [Conquer] effects.", 13.49, 18],
            ['OGN-287', 'Sigil of the Storm', $fre, 'rare', 0, 0, 0, "BATTLEFIELD: When you conquer here, recycle one of your runes.", 11.99, 24],
            ['OGN-288', 'Startipped Peak', $tar, 'rare', 0, 0, 0, "BATTLEFIELD: When you hold here, channel 1 rune exhausted.", 12.99, 20],
            ['OGN-289', 'Targon\'s Peak', $tar, 'rare', 0, 0, 0, "BATTLEFIELD: When you conquer here, ready 2 runes at end of turn.", 15.99, 15],
            ['OGN-290', 'The Arena\'s Greatest', $nox, 'rare', 0, 0, 0, "BATTLEFIELD: At start of phase, player gains 1 point.", 29.99, 5],
            ['OGN-291', 'The Candlelit Sanctum', $ion, 'rare', 0, 0, 0, "BATTLEFIELD: When you conquer, look at top 2, recycle or put back.", 12.99, 20],
            ['OGN-292', 'The Dreaming Tree', $ion, 'rare', 0, 0, 0, "BATTLEFIELD: First time you spell-choose a unit here, draw 1. (Note: Competitive Banned)", 14.49, 12],
            ['OGN-293', 'The Grand Plaza', $dem, 'rare', 0, 0, 0, "BATTLEFIELD: When you hold here with 7+ units, you win the game.", 49.99, 3],
            ['OGN-294', 'Trifarian War Camp', $nox, 'rare', 0, 0, 0, "BATTLEFIELD: Units here have +1 Might (includes attackers).", 18.99, 10],
            ['OGN-295', 'Vilemaw\'s Lair', $sha, 'rare', 0, 0, 0, "BATTLEFIELD: Units can\'t move from here to base.", 15.49, 15],
            ['OGN-296', 'Void Gate', $voi, 'rare', 0, 0, 0, "BATTLEFIELD: Spells/Abilities deal 1 Bonus Damage here.", 17.99, 14],
            ['OGN-297', 'Windswept Hillock', $ion, 'rare', 0, 0, 0, "BATTLEFIELD: Units here have [GANKING].", 13.99, 20],
            ['OGN-298', 'Zaun Warrens', $zau, 'rare', 0, 0, 0, "BATTLEFIELD: When you conquer here, discard 1, then draw 1.", 12.99, 22],
            ['OGN-299', 'Daughter of the Void', $voi, 'legendary', 0, 0, 0, "[REACTION] - [ADD] - [VOID]: Use to play spells. (Kai'Sa Legend)", 49.99, 5],
            ['OGN-300', 'Relentless Storm', $fre, 'legendary', 0, 0, 0, "[LEGEND] - [VOLIBEAR]. Play [MIGHTY] unit to channel 1 rune.", 49.99, 5],
            ['OGN-301', 'Loose Cannon', $zau, 'legendary', 0, 0, 0, "[LEGEND] - [JINX]. Start of phase draw 1 if hand is <= 1.", 49.99, 5],
            ['OGN-302', 'Hand of Noxus', $nox, 'legendary', 0, 0, 0, "[REACTION] - [LEGION] - [ADD]. Effect if played card this turn. (Darius Legend)", 49.99, 5],
            ['OGN-303', 'Nine-Tailed Fox', $ion, 'legendary', 0, 0, 0, "Enemy attacker gets -1 Power (min 1). (Ahri Legend)", 49.99, 5],
            ['OGN-304', 'Blind Monk', $ion, 'legendary', 0, 0, 0, "[Action]: Buff a friendly unit +1 Might. (Lee Sin Legend)", 49.99, 5],
            ['OGN-305', 'Unforgiven', $ion, 'legendary', 0, 0, 0, "[Action]: Move friendly unit to/from base. (Yasuo Legend)", 49.99, 5],
            ['OGN-306', 'Radiant Dawn', $tar, 'legendary', 0, 0, 0, "When you stun, buff friendly unit +1 Might. (Leona Legend)", 49.99, 5],
            ['OGN-307', 'Swift Scout', $ban, 'legendary', 0, 0, 0, "Pay Energy/Hide [HIDDEN]. [Action]: Recall Teemo to hand. (Teemo Legend)", 49.99, 5],
            ['OGN-308', 'Herald of Arcane', $zau, 'legendary', 0, 0, 0, "[Action]: Play a Recruit unit token. (Viktor Legend)", 49.99, 5],
            ['OGN-309', 'Bounty Hunter', $bil, 'legendary', 0, 0, 0, "[Action]: Give unit [GANKING] this turn. (Miss Fortune Legend)", 49.99, 5],
            ['OGN-310', 'The Boss', $ion, 'legendary', 0, 0, 0, "Spend buff to recall unit instead of dying. (Sett Legend)", 49.99, 5],
            ['TOKEN-01', 'Buff +1', $neu, 'common', 0, 0, 0, "Limit one buff per unit.", 0.00, 999],
            ['OGS-001', 'Annie', $nox, 'legendary', 5, 4, 4, "Your spells/abilities deal 1 Bonus Damage.", 29.99, 12],
            ['OGS-002', 'Firestorm', $nox, 'rare', 6, 0, 0, "(Spell) Deal 3 to all enemy units at a battlefield.", 8.49, 35],
            ['OGS-003', 'Incinerate', $nox, 'common', 2, 0, 0, "[Action] Deal 2 to a unit at a battlefield.", 1.99, 100],
            ['OGS-004', 'Master Yi', $ion, 'legendary', 5, 4, 4, "While you have 8+ runes, I have +4 Power.", 24.99, 14],
            ['OGS-005', 'Zephyr Sage', $ion, 'rare', 6, 6, 6, "[SHIELD] (+1 Might while defending).", 5.99, 45],
            ['OGS-006', 'Eye of the Dragon', $ion, 'common', 2, 2, 2, "When you play a spell, draw 1.", 2.49, 90],
            ['OGS-007', 'Twin Disciplines', $ion, 'common', 3, 0, 0, "Choose: +2 Power OR +1 Might this turn.", 1.99, 120],
            ['OGS-008', 'Dragon\'s Rage', $ion, 'common', 4, 0, 0, "Attacking friendly unit strikes enemy unit.", 2.99, 85],
            ['OGN-009', 'Garen', $dem, 'legendary', 6, 5, 5, "While defending, +1 Might and [Shield].", 21.99, 16],
            ['OGN-277b', 'Aspirant\'s Climb (Bundle)', $tar, 'rare', 0, 0, 0, "(Worlds 2025 Bundle Card Art Variant) BATTLEFIELD: Increase points needed to win by 1.", 24.99, 5],
            ['OGN-278b', 'Back-Alley Bar (Bundle)', $zau, 'rare', 0, 0, 0, "(Worlds 2025 Bundle Card Art Variant) BATTLEFIELD: +1 Might when moving from here.", 22.99, 5],
            ['OGN-279b', 'Bandle Tree (Bundle)', $ban, 'rare', 0, 0, 0, "(Worlds 2025 Bundle Card Art Variant) BATTLEFIELD: Hide an additional card here.", 25.99, 5],
            ['OGN-280b', 'Fortified Position (Bundle)', $dem, 'rare', 0, 0, 0, "(Worlds 2025 Bundle Card Art Variant) BATTLEFIELD: SHIELD 2 when defending.", 21.99, 5],
            ['OGN-281b', 'Grove of the God-Willow (Bundle)', $ion, 'rare', 0, 0, 0, "(Worlds 2025 Bundle Card Art Variant) BATTLEFIELD: Draw 1 when holding.", 23.99, 5],
            ['OGN-282b', 'Hallowed Tomb (Bundle)', $sha, 'rare', 0, 0, 0, "(Worlds 2025 Bundle Card Art Variant) BATTLEFIELD: Return Champion from trash.", 26.99, 5],
            ['OGN-293b', 'The Grand Plaza (Bundle)', $dem, 'rare', 0, 0, 0, "(Worlds 2025 Bundle Card Art Variant) BATTLEFIELD: Win game with 7+ units.", 59.99, 2],
            ['OGN-294b', 'Trifarian War Camp (Bundle)', $nox, 'rare', 0, 0, 0, "(Worlds 2025 Bundle Card Art Variant) BATTLEFIELD: +1 Might here.", 28.99, 5],
            ['OGN-299s', 'Daughter of the Void (Sig)', $voi, 'legendary', 0, 0, 0, "(Signature Variant) [REACTION] - [ADD] - [VOID]: Use to play spells.", 79.99, 2],
            ['OGN-300s', 'Relentless Storm (Sig)', $fre, 'legendary', 0, 0, 0, "(Signature Variant) [LEGEND] - [VOLIBEAR]. Channel on MIGHTY unit.", 79.99, 2],
            ['OGN-301s', 'Loose Cannon (Sig)', $zau, 'legendary', 0, 0, 0, "(Signature Variant) [LEGEND] - [JINX]. Start of phase draw 1.", 79.99, 2],
            ['OGN-302s', 'Hand of Noxus (Sig)', $nox, 'legendary', 0, 0, 0, "(Signature Variant) [REACTION] - [LEGION] - [ADD].", 79.99, 2],
            ['OGN-303s', 'Nine-Tailed Fox (Sig)', $ion, 'legendary', 0, 0, 0, "(Signature Variant) Enemy attacker gets -1 Power.", 79.99, 2],
            ['OGN-304s', 'Blind Monk (Sig)', $ion, 'legendary', 0, 0, 0, "(Signature Variant) [Action]: Buff friendly unit +1 Might.", 79.99, 2],
            ['OGN-305s', 'Unforgiven (Sig)', $ion, 'legendary', 0, 0, 0, "(Signature Variant) [Action]: Move friendly unit.", 79.99, 2],
            ['OGN-306s', 'Radiant Dawn (Sig)', $tar, 'legendary', 0, 0, 0, "(Signature Variant) Buff friendly unit when you stun.", 79.99, 2],
            ['OGN-307s', 'Swift Scout (Sig)', $ban, 'legendary', 0, 0, 0, "(Signature Variant) Recall Teemo to hand.", 79.99, 2],
            ['OGN-308s', 'Herald of Arcane (Sig)', $zau, 'legendary', 0, 0, 0, "(Signature Variant) [Action]: Play a Recruit token.", 79.99, 2],
            ['OGN-309s', 'Bounty Hunter (Sig)', $bil, 'legendary', 0, 0, 0, "(Signature Variant) [Action]: Give unit [GANKING].", 79.99, 2],
            ['OGS-010', 'Judgment', $dem, 'rare', 8, 0, 0, "(Spell) A friendly unit strikes all enemy units here.", 9.99, 25],
            ['OGS-011', 'Single Combat', $dem, 'common', 2, 0, 0, "[REACTION] Two units strike each other.", 1.49, 150],
            ['OGS-012', 'Relentless Pursuit', $dem, 'common', 3, 0, 0, "[Action] Ready all units.", 2.49, 90],
            ['OGS-013', 'Braum', $fre, 'legendary', 4, 0, 5, "[TANK] [REGENERATION] (Ready at start of phase).", 22.99, 14],
            ['OGS-014', 'Take Heart', $fre, 'rare', 3, 0, 0, "(Spell) Grant a damaged unit +3 Might.", 4.49, 60],
            ['OGS-015', 'Troll Chant', $fre, 'common', 2, 0, 0, "[REACTION] Ally +1 Might, Enemy -1 Might this turn.", 1.29, 180],
            ['OGS-016', 'Stalwart Poro', $fre, 'common', 2, 2, 2, "[SHIELD] (+1 Might while defending).", 1.49, 200],
            ['OGS-017', 'Elise', $sha, 'legendary', 2, 2, 3, "When I attack, play a 1/1 Spiderling unit token.", 24.99, 12],
            ['OGS-018', 'Vile Feast', $sha, 'common', 2, 0, 0, "[Action] Deal 1 to a unit and play a 1/1 Spiderling.", 1.99, 140],
            ['OGS-019', 'Glimpse Beyond', $sha, 'common', 2, 0, 0, "[Action] Kill a friendly unit to draw 2.", 2.49, 110],
            ['OGS-020', 'Crawling Sensation', $sha, 'common', 1, 0, 0, "If a friendly unit died this turn, play 2 Spiderlings.", 1.49, 160],
            ['OGS-021', 'Lady Luminosity', $dem, 'legendary', 6, 5, 5, "(Art Variant) Lux. Barrier. When I see you play 6+ Energy in spells, play a Final Spark.", 34.99, 5],
            ['OGS-022', 'Final Spark', $dem, 'rare', 6, 0, 0, "[Action] Deal 4 to an enemy. If I kill it, deal 2 to the enemy Nexus.", 4.99, 40],
            ['OGS-023', 'Might of Demacia', $dem, 'legendary', 6, 0, 0, "[Action] Grant all allies +3/+3 and OVERWHELM this turn.", 12.99, 15],
            ['OGS-024', 'Decisive Strike', $dem, 'rare', 6, 0, 0, "[Action] Silence an enemy unit this turn and strike it.", 3.49, 75],
            ['STD-001', 'Against the Odds', $tar, 'common', 3, 0, 0, "[REACTION] Give an ally +2 Power for each enemy unit here this turn.", 1.49, 200],
            ['STD-002', 'Armed Assailant', $nox, 'common', 2, 2, 2, "When I'm played, grant me +1/+1 if you've played another card.", 1.99, 120],
            ['STD-003', 'Blood Rush', $nox, 'common', 2, 0, 0, "[Action] Give a unit +2 Power and OVERWHELM this turn.", 1.49, 150],
            ['STD-004', 'Bushwhack', $ion, 'common', 1, 0, 0, "[Action] Trap an enemy unit. It can't move or block this turn.", 1.29, 180],
            ['STD-005', 'Detonate', $zau, 'common', 3, 0, 0, "[Action] Sacrifice a Scrap gear to deal 4 damage to a unit.", 2.49, 95],
            ['STD-006', 'Eager Drakehound', $nox, 'common', 3, 3, 3, "I enter ready.", 2.99, 85],
            ['STD-007', 'Gem Jammer', $tar, 'common', 4, 4, 4, "When I'm played, grant an ally SHIELD 1.", 3.99, 65],
            ['STD-008', 'Sentinel Adept', $sha, 'common', 1, 2, 2, "FEARSOME (Only units with 3+ Might can block me).", 1.29, 200],
            ['STD-009', 'Serrated Dirk', $bil, 'common', 1, 0, 0, "[Gear] Grant me +1 Power.", 0.99, 300],
            ['STD-010', 'Void Drone', $voi, 'common', 2, 1, 1, "When I see an ally with a keyword, I gain it.", 1.49, 160],
            ['STD-011', 'Angle Shot', $bil, 'common', 2, 0, 0, "[Action] Deal 2 to a unit. If it's in base, deal 3 instead.", 1.99, 130],
            ['STD-012', 'Battering Ram', $nox, 'common', 6, 0, 8, "OVERWHELM. When I attack, grant me +4 Power.", 4.49, 52],
            ['STD-013', 'Blast Corps Cadet', $zau, 'common', 3, 3, 1, "DEATHKELL: Deal 1 to the enemy Nexus.", 1.29, 180],
            ['STD-014', 'Brash Gambler', $bil, 'common', 4, 4, 3, "When I'm played, discard 1 to draw 1.", 2.49, 92],
            ['STD-015', 'Cithria (STD)', $dem, 'rare', 1, 2, 2, "The start of a legend.", 3.99, 60],
            ['STD-016', 'Confront', $dem, 'common', 2, 0, 0, "[Action] Choose an enemy to block a friendly unit this turn.", 1.49, 150],
            ['STD-017', 'Death Mark', $ion, 'rare', 3, 0, 0, "[Action] Remove EPHEMERAL from an ally and give it to an enemy.", 4.99, 45],
            ['STD-018', 'Deep Meditation', $ion, 'rare', 4, 0, 0, "[Action] Draw 2 spells. If you've played 2+ spells this turn, I cost 2 less.", 5.49, 38],
            ['STD-019', 'Disarm', $dem, 'common', 1, 0, 0, "[REACTION] Remove all Power from an enemy unit this turn.", 1.29, 190],
            ['STD-020', 'Draven (STD)', $nox, 'legendary', 3, 3, 3, "QUICK ATTACK. When I'm played or attack, create a Spinning Axe in hand.", 24.99, 12],
            ['STD-021', 'Elixir of Iron', $fre, 'common', 1, 0, 0, "[REACTION] Give an ally +2 Might this turn.", 0.99, 250],
            ['STD-022', 'Excited!', $zau, 'rare', 3, 0, 0, "[Action] Discard 1 to deal 3 damage to anything.", 3.49, 88],
            ['STD-023', 'Feast', $sha, 'rare', 2, 0, 0, "[Action] Deal 1 to a unit and heal your Nexus 2.", 2.99, 105],
            ['STD-024', 'Rell (STD)', $nox, 'legendary', 4, 4, 5, "CHALLENGER. ATTRACT (Enemies must block me if possible).", 22.99, 14],
            ['STD-025', 'Twin Disciplines', $ion, 'common', 2, 0, 0, "[REACTION] Give an ally +2 Power or +3 Might this turn.", 1.99, 140],
        ];

        foreach ($cards as [$id, $name, $cat, $rarity, $energy, $power, $might, $desc, $price, $stock]) {
            Product::updateOrCreate(
                ['card_id' => $id],
                [
                    'category_id' => $cat,
                    'name'        => $name,
                    'slug'        => Str::slug($name . '-' . $id),
                    'card_id'     => $id,
                    'description' => $desc,
                    'energy'      => $energy,
                    'power'       => $power,
                    'might'       => $might,
                    'rarity'      => $rarity,
                    'price'       => $price,
                    'stock'       => $stock,
                    'image'       => self::CDN . $id . '.webp',
                    'badge'       => $rarity === 'legendary' ? 'legendary' : ($rarity === 'epic' ? 'epic' : ($rarity === 'rare' ? 'rare' : 'none')),
                    'is_active'   => true,
                    'is_featured' => $rarity === 'legendary',
                ]
            );
        }

        $this->command->info('Seeded ' . count($cards) . ' verified Riftbound cards.');
    }
}
